### ISSUE TITLE
Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by hanglearning** [aaronpk/checks#3]
Hello aaronpk, thanks for the code! While I try to run `$ php checks.php`, I got this error

`PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /Users/chenhang/Downloads/checks-master/lib/fpdf.inc.php on line 432`

I am using macOS and my `$php -v` returns the following messages

`Zend Engine v4.2.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.2, Copyright (c), by Zend Technologies`

I rarely use PHP and some stackoverflow searches didn't help me fix this issue. Could you take a look? Or did I run the program correctly? Thanks.

**Comment by aaronpk** [comment]
Ah shoot, looks like the PDF library I'm using doesn't support PHP 8! I'm going to have to update it. In the mean time, you should be able to install PHP 7.4 using Homebrew to run it

**Comment by hanglearning** [comment]
Thank you very much for your prompt reply! However, PHP 7.4 returns the same issue. The version that works for me is 5.6. The PDF looks so good! Thank you again you potentially saved my money to buy checks for life! 🙌
